version: '3.8'

services:
  api:
    build: .
    ports:
      - "8100:8100"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
